openapi: 3.0.3
security: []
servers:
  - description:  Culture Matcher API.
    url: http://localhost:3000
info:
  description: External culture fit endpoints to be consumed by the client.
  title: Culture Matcher
  version: 1.0.0
paths:
  /api/v1/culture_types:
    get:
      $ref: ./schemas/index_culture_types.yaml
    post:
      $ref: ./schemas/create_culture_types.yaml
  /api/v1/culture_types/{id}:
    get:
      $ref: ./schemas/show_culture_types.yaml
    put:
      $ref: ./schemas/update_culture_types.yaml
    delete:
      $ref: ./schemas/destroy_culture_types.yaml
  /api/v1/applicants:
    get:
      $ref: ./schemas/index_applicants.yaml
    post:
      $ref: ./schemas/create_applicants.yaml
  /api/v1/applicants/{id}:
    get:
      $ref: ./schemas/show_applicants.yaml
    put:
      $ref: ./schemas/update_applicants.yaml
    delete:
      $ref: ./schemas/destroy_applicants.yaml
  /api/v1/companies:
    get:
      $ref: ./schemas/index_companies.yaml
    post:
      $ref: ./schemas/create_companies.yaml
  /api/v1/companies/{id}:
    get:
      $ref: ./schemas/show_companies.yaml
    put:
      $ref: ./schemas/update_companies.yaml
    delete:
      $ref: ./schemas/destroy_companies.yaml
  /api/v1/matches:
    get:
      $ref: ./schemas/index_matches.yaml
    post:
      $ref: ./schemas/create_matches.yaml
  /api/v1/matches/{id}:
    get:
      $ref: ./schemas/show_matches.yaml
    put:
      $ref: ./schemas/update_matches.yaml
    delete:
      $ref: ./schemas/destroy_matches.yaml