default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: postgres
  username: <%= Rails.application.credentials.postgres[:username] %>
  password: <%= Rails.application.credentials.postgres[:password] %>

development:
  <<: *default
  database: <%= Rails.application.credentials.postgres[:database] %>_development

test:
  <<: *default
  database: <%= Rails.application.credentials.postgres[:database] %>_test

production:
  <<: *default
  database: <%= Rails.application.credentials.postgres[:database] %>_production
